Attempt to pin value, ran into errors
Actual error:
```
2026-02-12T22:13:47.307781Z DEBUG zksync_os_server::prover_input_generator: ProverInputGenerator started processing block 1 with 1 transactions block_number=1
ZK RISC-V simulator is starting
[/home/evl/.cargo/git/checkouts/zksync-airbender-8ab8222a00c65218/c23fd00/risc_v_simulator/src/sim/mod.rs:192:13] path.as_ref() = "./db/node1/app_bins/v6/singleblock_batch.bin"

thread 'tokio-runtime-worker' (346892) panicked at /home/evl/.cargo/git/checkouts/zksync-airbender-8ab8222a00c65218/c23fd00/risc_v_simulator/src/sim/mod.rs:197:13:
assertion `left == right` failed
  left: 1
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2026-02-12T22:13:47.308723Z ERROR zksync_os_pipeline::builder: prover_input_generator component failed err=task 107 panicked with message "assertion `left == right` failed\n  left: 1\n right: 0"
2026-02-12T22:13:47.308756Z ERROR zksync_os_pipeline::builder: batcher component failed err=batcher inbound channel unexpectedly closed
2026-02-12T22:13:47.308775Z  WARN zksync_os_pipeline::builder: batch_verification component unexpectedly exited
2026-02-12T22:13:47.308779Z  INFO zksync_os_server: One of the subsystems exited - exiting process.
2026-02-12T22:13:47.308792Z ERROR zksync_os_pipeline::builder: fri_proving component failed err=FRI proving input stream ended unexpectedly
2026-02-12T22:13:47.308811Z ERROR zksync_os_pipeline::builder: gapless_committer component failed err=GaplessCommitter input stream ended unexpectedly
2026-02-12T22:13:47.308839Z ERROR zksync_os_pipeline::builder: upgrade_gatekeeper component failed err=UpgradeGatekeeper input stream ended unexpectedly
2026-02-12T22:13:47.308859Z ERROR zksync_os_pipeline::builder: commit component failed err=inbound channel closed
2026-02-12T22:13:47.308874Z ERROR zksync_os_pipeline::builder: snark_proving component failed err=SNARK proving input stream ended unexpectedly
2026-02-12T22:13:47.308894Z ERROR zksync_os_pipeline::builder: gapless_l1_proof_sender component failed err=GaplessL1ProofSender input stream ended unexpectedly
2026-02-12T22:13:47.309004Z  WARN zksync_os_server: Main task unexpectedly exited
2026-02-12T22:13:47.309049Z DEBUG zksync_os_sequencer::execution::block_executor: stream exhausted → sealing block_number=2 txs=6
2026-02-12T22:13:47.309123Z  INFO zksync_os_sequencer::execution: Saving dump..
2026-02-12T22:13:47.315872Z ERROR zksync_os_pipeline::builder: sequencer component failed err=execute_block
```

I believe the problem is wrong app.bin after all my changes (especially
around simulation). The simulation doesn't have a branch so I tried to
overwrite it with older version (assuming it might just work, but it
doesn't).